window.WP_MUSEUM_RELEASES = [
	{
		version: '6.2',
		name: 'Dolphy',
		musician: 'Eric Dolphy',
		released: 'March 29, 2023',
		year: 2023,
		era: 'Blocks Everywhere',
		knownFor: 'Site Editor leaves beta',
		detail: 'The Site Editor became a first-class experience with the Style Book, Openverse in the inserter, sticky positioning, custom CSS, and smoother block theme editing.',
		artifact: 'Style Book cabinet',
		blueprint: './blueprints/wordpress-museum/wp-6-2.json',
	},
	{
		version: '6.1',
		name: 'Misha',
		musician: 'Mikhail Alperin',
		released: 'November 1, 2022',
		year: 2022,
		era: 'Blocks Everywhere',
		knownFor: 'Fluid typography and style variations',
		detail: 'Twenty Twenty-Three shipped with style variations while block tooling added better templates, layout controls, and a more confident writing flow.',
		artifact: 'Typographic tide pool',
		blueprint: './blueprints/wordpress-museum/wp-6-1.json',
	},
	{
		version: '6.0',
		name: 'Arturo',
		musician: "Arturo O'Farrill",
		released: 'May 24, 2022',
		year: 2022,
		era: 'Blocks Everywhere',
		knownFor: 'Block locking and broader site editing',
		detail: 'WordPress expanded full site editing with block locking, style switching, improved writing tools, and more template control.',
		artifact: 'Locked block display case',
		blueprint: './blueprints/wordpress-museum/wp-6-0.json',
	},
	{
		version: '5.9',
		name: 'Josephine',
		musician: 'Josephine Baker',
		released: 'January 25, 2022',
		year: 2022,
		era: 'Blocks Everywhere',
		knownFor: 'Full Site Editing arrives',
		detail: 'The first default block theme, Twenty Twenty-Two, brought theme.json, template parts, and the new Site Editor into core.',
		artifact: 'Template-part terrarium',
		blueprint: './blueprints/wordpress-museum/wp-5-9.json',
	},
	{
		version: '5.8',
		name: 'Tatum',
		musician: 'Art Tatum',
		released: 'July 20, 2021',
		year: 2021,
		era: 'Blocks Everywhere',
		knownFor: 'Blocks enter widgets',
		detail: 'Block-based widgets, template editing, WebP support, query loop blocks, and theme.json pushed blocks outside the post editor.',
		artifact: 'Sidebar block aquarium',
		blueprint: './blueprints/wordpress-museum/wp-5-8.json',
	},
	{
		version: '5.7',
		name: 'Esperanza',
		musician: 'Esperanza Spalding',
		released: 'March 9, 2021',
		year: 2021,
		era: 'Blocks Everywhere',
		knownFor: 'One-click HTTP to HTTPS',
		detail: 'WordPress added an easier HTTP-to-HTTPS switch, lazy-loaded iframes, editor refinements, and color palette tooling.',
		artifact: 'HTTPS light switch',
		blueprint: './blueprints/wordpress-museum/wp-5-7.json',
	},
	{
		version: '5.6',
		name: 'Simone',
		musician: 'Nina Simone',
		released: 'December 8, 2020',
		year: 2020,
		era: 'Blocks Everywhere',
		knownFor: 'Application passwords',
		detail: 'Application passwords, PHP 8 compatibility work, auto-update controls, and Twenty Twenty-One arrived together.',
		artifact: 'API passport booth',
		blueprint: './blueprints/wordpress-museum/wp-5-6.json',
	},
	{
		version: '5.5',
		name: 'Eckstine',
		musician: 'Billy Eckstine',
		released: 'August 11, 2020',
		year: 2020,
		era: 'Blocks Everywhere',
		knownFor: 'Lazy images and block patterns',
		detail: 'Images lazy-loaded by default, XML sitemaps joined core, and block patterns made reusable layout ideas visible.',
		artifact: 'Lazy image hammock',
		blueprint: './blueprints/wordpress-museum/wp-5-5.json',
	},
	{
		version: '5.4',
		name: 'Adderley',
		musician: 'Nat Adderley',
		released: 'March 31, 2020',
		year: 2020,
		era: 'Block Editor',
		knownFor: 'Fullscreen block editor by default',
		detail: 'The block editor gained fullscreen default mode, Buttons and Social Icons blocks, cleaner navigation, and privacy improvements.',
		artifact: 'Fullscreen writing booth',
		blueprint: './blueprints/wordpress-museum/wp-5-4.json',
	},
	{
		version: '5.3',
		name: 'Kirk',
		musician: 'Rahsaan Roland Kirk',
		released: 'November 12, 2019',
		year: 2019,
		era: 'Block Editor',
		knownFor: 'Large image handling',
		detail: 'Large image handling, the Group block, admin email verification, and the Twenty Twenty theme refined the post-Gutenberg baseline.',
		artifact: 'Oversized JPEG coat check',
		blueprint: './blueprints/wordpress-museum/wp-5-3.json',
	},
	{
		version: '5.2',
		name: 'Jaco',
		musician: 'Jaco Pastorius',
		released: 'May 7, 2019',
		year: 2019,
		era: 'Block Editor',
		knownFor: 'Site Health and fatal error recovery',
		detail: 'Site Health, fatal error protection, and PHP version nudges made WordPress more diagnostic and more forgiving.',
		artifact: 'Dashboard stethoscope',
		blueprint: './blueprints/wordpress-museum/wp-5-2.json',
	},
	{
		version: '5.1',
		name: 'Betty',
		musician: 'Betty Carter',
		released: 'February 21, 2019',
		year: 2019,
		era: 'Block Editor',
		knownFor: 'Post-Gutenberg performance polish',
		detail: 'The block editor got faster, and the dashboard began nudging site owners away from old PHP versions.',
		artifact: 'PHP nudge postcard',
		blueprint: './blueprints/wordpress-museum/wp-5-1.json',
	},
	{
		version: '5.0',
		name: 'Bebo',
		musician: 'Bebo Valdes',
		released: 'December 6, 2018',
		year: 2018,
		era: 'Block Editor',
		knownFor: 'The block editor lands',
		detail: 'Gutenberg replaced the classic editor for new sites, turning content into movable blocks and setting a new direction for WordPress.',
		artifact: 'Block party turnstile',
		blueprint: './blueprints/wordpress-museum/wp-5-0.json',
	},
	{
		version: '4.9',
		name: 'Tipton',
		musician: 'Billy Tipton',
		released: 'November 15, 2017',
		year: 2017,
		era: 'API and Customizer',
		knownFor: 'Customizer drafts and scheduling',
		detail: 'Design changes could be drafted, scheduled, previewed, and shared, while code editing gained syntax highlighting and linting.',
		artifact: 'Scheduled CSS helmet',
		blueprint: './blueprints/wordpress-museum/wp-4-9.json',
	},
	{
		version: '4.8',
		name: 'Evans',
		musician: 'Bill Evans',
		released: 'June 8, 2017',
		year: 2017,
		era: 'API and Customizer',
		knownFor: 'Media widgets',
		detail: 'Image, video, audio, and rich text widgets made sidebars friendlier without requiring a shortcode séance.',
		artifact: 'Widget media lounge',
		blueprint: './blueprints/wordpress-museum/wp-4-8.json',
	},
	{
		version: '4.7',
		name: 'Vaughan',
		musician: 'Sarah Vaughan',
		released: 'December 6, 2016',
		year: 2016,
		era: 'API and Customizer',
		knownFor: 'REST API content endpoints',
		detail: 'REST API content endpoints opened a modern integration path while Twenty Seventeen, starter content, and video headers polished first-run setup.',
		artifact: 'JSON side door',
		blueprint: './blueprints/wordpress-museum/wp-4-7.json',
	},
	{
		version: '4.6',
		name: 'Pepper',
		musician: 'Pepper Adams',
		released: 'August 16, 2016',
		year: 2016,
		era: 'API and Customizer',
		knownFor: 'Native fonts and streamlined updates',
		detail: 'Native system fonts, better plugin/theme updates, editor link checks, and content recovery made wp-admin feel lighter.',
		artifact: 'Native font specimen',
		blueprint: './blueprints/wordpress-museum/wp-4-6.json',
	},
	{
		version: '4.5',
		name: 'Coleman',
		musician: 'Coleman Hawkins',
		released: 'April 12, 2016',
		year: 2016,
		era: 'API and Customizer',
		knownFor: 'Inline links and responsive preview',
		detail: 'Inline link editing, responsive Customizer previews, custom logos, and smarter image compression improved everyday site tuning.',
		artifact: 'Responsive preview periscope',
		blueprint: './blueprints/wordpress-museum/wp-4-5.json',
	},
	{
		version: '4.4',
		name: 'Clifford',
		musician: 'Clifford Brown',
		released: 'December 8, 2015',
		year: 2015,
		era: 'API and Customizer',
		knownFor: 'Responsive images',
		detail: 'Responsive images, embeddable posts, REST API infrastructure, and Twenty Sixteen made WordPress speak more like the modern web.',
		artifact: 'Srcset specimen drawer',
		blueprint: './blueprints/wordpress-museum/wp-4-4.json',
	},
	{
		version: '4.3',
		name: 'Billie',
		musician: 'Billie Holiday',
		released: 'August 18, 2015',
		year: 2015,
		era: 'Modern Admin',
		knownFor: 'Menus in the Customizer',
		detail: 'Menus moved into the Customizer; site icons, stronger passwords, and formatting shortcuts smoothed daily publishing.',
		artifact: 'Favicon valet stand',
		blueprint: './blueprints/wordpress-museum/wp-4-3.json',
	},
	{
		version: '4.2',
		name: 'Powell',
		musician: 'Bud Powell',
		released: 'April 23, 2015',
		year: 2015,
		era: 'Modern Admin',
		knownFor: 'Emoji and extended characters',
		detail: 'Emoji support, better character handling, Press This improvements, and smoother plugin updates made publishing more portable.',
		artifact: 'Unicode display cabinet',
		blueprint: './blueprints/wordpress-museum/wp-4-2.json',
	},
	{
		version: '4.1',
		name: 'Dinah',
		musician: 'Dinah Washington',
		released: 'December 18, 2014',
		year: 2014,
		era: 'Modern Admin',
		knownFor: 'Distraction-free writing polish',
		detail: 'Twenty Fifteen, language installs from settings, and a calmer writing surface made WordPress feel more focused.',
		artifact: 'Quiet writing alcove',
		blueprint: './blueprints/wordpress-museum/wp-4-1.json',
	},
	{
		version: '4.0',
		name: 'Benny',
		musician: 'Benny Goodman',
		released: 'September 4, 2014',
		year: 2014,
		era: 'Modern Admin',
		knownFor: 'Media grid and embed previews',
		detail: 'The media library gained a grid, embeds previewed in the editor, and plugin discovery became more visual.',
		artifact: 'Media grid wall',
		blueprint: './blueprints/wordpress-museum/wp-4-0.json',
	},
	{
		version: '3.9',
		name: 'Smith',
		musician: 'Jimmy Smith',
		released: 'April 16, 2014',
		year: 2014,
		era: 'Modern Admin',
		knownFor: 'Visual editor refresh',
		detail: 'Improved TinyMCE, drag-and-drop images, gallery previews, audio/video playlists, and live widget previews made editing more tactile.',
		artifact: 'TinyMCE tune-up bench',
		blueprint: './blueprints/wordpress-museum/wp-3-9.json',
	},
	{
		version: '3.8',
		name: 'Parker',
		musician: 'Charlie Parker',
		released: 'December 12, 2013',
		year: 2013,
		era: 'Modern Admin',
		knownFor: 'MP6 responsive admin redesign',
		detail: 'The dashboard got a modern responsive design, Open Sans, admin color schemes, and the Twenty Fourteen magazine theme.',
		artifact: 'Admin color swatch rack',
		blueprint: './blueprints/wordpress-museum/wp-3-8.json',
	},
	{
		version: '3.7',
		name: 'Basie',
		musician: 'Count Basie',
		released: 'October 24, 2013',
		year: 2013,
		era: 'Modern Admin',
		knownFor: 'Automatic maintenance updates',
		detail: 'Background updates, stronger password recommendations, and better search put WordPress on a path toward self-maintenance.',
		artifact: 'Night-shift updater cart',
		blueprint: './blueprints/wordpress-museum/wp-3-7.json',
	},
	{
		version: '3.6',
		name: 'Oscar',
		musician: 'Oscar Peterson',
		released: 'August 1, 2013',
		year: 2013,
		era: 'Modern Admin',
		knownFor: 'Improved revisions and autosave',
		detail: 'Post revisions, autosave, post locking, native audio/video embeds, and Twenty Thirteen protected writers from accidents.',
		artifact: 'Revision time machine',
		blueprint: './blueprints/wordpress-museum/wp-3-6.json',
	},
	{
		version: '3.5',
		name: 'Elvin',
		musician: 'Elvin Jones',
		released: 'December 11, 2012',
		year: 2012,
		era: 'CMS Toolkit',
		knownFor: 'New media manager',
		detail: 'The media workflow was rebuilt with a cleaner modal, Retina-ready admin assets, and a simpler upload experience.',
		artifact: 'Retina media loupe',
		blueprint: './blueprints/wordpress-museum/wp-3-5.json',
	},
	{
		version: '3.4',
		name: 'Green',
		musician: 'Grant Green',
		released: 'June 13, 2012',
		year: 2012,
		era: 'CMS Toolkit',
		knownFor: 'Theme Customizer',
		detail: 'Live theme preview, the Customizer, Twitter embeds, and better image captions let site owners rehearse changes first.',
		artifact: 'Theme dressing room',
		blueprint: './blueprints/wordpress-museum/wp-3-4.json',
	},
	{
		version: '3.3',
		name: 'Sonny',
		musician: 'Sonny Stitt',
		released: 'December 12, 2011',
		year: 2011,
		era: 'CMS Toolkit',
		knownFor: 'Drag-and-drop uploads',
		detail: 'Drag-and-drop media upload, flyout admin menus, an improved toolbar, and feature pointers made admin life friendlier.',
		artifact: 'Upload drop zone',
		blueprint: './blueprints/wordpress-museum/wp-3-3.json',
	},
	{
		version: '3.2',
		name: 'Gershwin',
		musician: 'George Gershwin',
		released: 'July 4, 2011',
		year: 2011,
		era: 'CMS Toolkit',
		knownFor: 'Faster, leaner WordPress',
		detail: 'WordPress dropped old PHP/MySQL support, added distraction-free writing, and shipped Twenty Eleven.',
		artifact: 'IE6 retirement placard',
		blueprint: './blueprints/wordpress-museum/wp-3-2.json',
	},
	{
		version: '3.1',
		name: 'Reinhardt',
		musician: 'Django Reinhardt',
		released: 'February 23, 2011',
		year: 2011,
		era: 'CMS Toolkit',
		knownFor: 'Admin bar and post formats',
		detail: 'The admin bar, post formats, internal linking, and archive pages for custom content types made sites feel more connected.',
		artifact: 'Admin bar overhead rail',
		blueprint: './blueprints/wordpress-museum/wp-3-1.json',
	},
	{
		version: '3.0',
		name: 'Thelonious',
		musician: 'Thelonious Monk',
		released: 'June 17, 2010',
		year: 2010,
		era: 'CMS Toolkit',
		knownFor: 'Custom post types and multisite merge',
		detail: 'Custom post types, custom taxonomies, menus, multisite, custom backgrounds, custom headers, and Twenty Ten made WordPress a broader CMS.',
		artifact: 'Custom post type passport',
		blueprint: './blueprints/wordpress-museum/wp-3-0.json',
	},
	{
		version: '2.9',
		name: 'Carmen',
		musician: 'Carmen McRae',
		released: 'December 18, 2009',
		year: 2009,
		era: 'Dashboard Foundations',
		knownFor: 'Trash, undo, and image editing',
		detail: 'Trash made deletion less dramatic, while image editing, oEmbeds, batch plugin updates, and post thumbnails improved publishing.',
		artifact: 'Trash can with velvet rope',
		blueprint: './blueprints/wordpress-museum/wp-2-9.json',
	},
	{
		version: '2.8',
		name: 'Baker',
		musician: 'Chet Baker',
		released: 'June 11, 2009',
		year: 2009,
		era: 'Dashboard Foundations',
		knownFor: 'Theme installer',
		detail: 'Theme browsing and installation moved into the dashboard, widgets improved, and admin pages got faster.',
		artifact: 'Theme suitcase carousel',
		blueprint: './blueprints/wordpress-museum/wp-2-8.json',
	},
	{
		version: '2.7',
		name: 'Coltrane',
		musician: 'John Coltrane',
		released: 'December 10, 2008',
		year: 2008,
		era: 'Dashboard Foundations',
		knownFor: 'Modern dashboard layout',
		detail: 'The admin redesign moved navigation to the side and added automatic upgrades, threaded comments, and sticky posts.',
		artifact: 'Side-menu monument',
		blueprint: './blueprints/wordpress-museum/wp-2-7.json',
	},
	{
		version: '2.6',
		name: 'Tyner',
		musician: 'McCoy Tyner',
		released: 'July 15, 2008',
		year: 2008,
		era: 'Dashboard Foundations',
		knownFor: 'Post revisions',
		detail: 'Post revisions, Press This, image captions, word count, and theme previews gave writers a stronger safety net.',
		artifact: 'Draft memory cabinet',
		blueprint: './blueprints/wordpress-museum/wp-2-6.json',
	},
	{
		version: '2.5',
		name: 'Brecker',
		musician: 'Michael Brecker',
		released: 'March 29, 2008',
		year: 2008,
		era: 'Dashboard Foundations',
		knownFor: 'Major admin redesign and media uploader',
		detail: 'The dashboard was redesigned; the media uploader, galleries, shortcodes, Gravatar support, and plugin update flow improved.',
		artifact: 'Multi-file uploader kiosk',
		blueprint: './blueprints/wordpress-museum/wp-2-5.json',
	},
	{
		version: '2.3',
		name: 'Dexter',
		musician: 'Dexter Gordon',
		released: 'September 24, 2007',
		year: 2007,
		era: 'Dashboard Foundations',
		knownFor: 'Native tags',
		detail: 'Tags joined core, update notifications got better, canonical URLs arrived, and taxonomy started getting more serious.',
		artifact: 'Tag cloud specimen jar',
		blueprint: './blueprints/wordpress-museum/wp-2-3.json',
	},
	{
		version: '2.2',
		name: 'Getz',
		musician: 'Stan Getz',
		released: 'May 16, 2007',
		year: 2007,
		era: 'Dashboard Foundations',
		knownFor: 'Widgets in core',
		detail: 'Sidebar widgets became core, Atom feed handling improved, and mail features got sturdier.',
		artifact: 'Sidebar widget clubhouse',
		blueprint: './blueprints/wordpress-museum/wp-2-2.json',
	},
	{
		version: '2.1',
		name: 'Ella',
		musician: 'Ella Fitzgerald',
		released: 'January 22, 2007',
		year: 2007,
		era: 'Dashboard Foundations',
		knownFor: 'Autosave and spell check',
		detail: 'Autosave, spell checking, a new uploader, privacy options, and cleaner database code helped early bloggers lose less work.',
		artifact: 'Autosave umbrella stand',
		blueprint: './blueprints/wordpress-museum/wp-2-1.json',
	},
	{
		version: '2.0',
		name: 'Duke',
		musician: 'Duke Ellington',
		released: 'December 31, 2005',
		year: 2005,
		era: 'Blogging Roots',
		knownFor: 'Rich editor, roles, and Akismet',
		detail: 'TinyMCE, user roles, bundled Akismet, image uploading, and a refreshed admin made WordPress feel more grown up.',
		artifact: 'WYSIWYG New Years hat',
		blueprint: './blueprints/wordpress-museum/wp-2-0.json',
	},
	{
		version: '1.5',
		name: 'Strayhorn',
		musician: 'Billy Strayhorn',
		released: 'February 17, 2005',
		year: 2005,
		era: 'Blogging Roots',
		knownFor: 'Themes and Pages',
		detail: 'The theme system, static Pages, Kubrick, and template files made customization possible without editing core.',
		artifact: 'Kubrick wallpaper sample',
		blueprint: './blueprints/wordpress-museum/wp-1-5.json',
	},
	{
		version: '1.2',
		name: 'Mingus',
		musician: 'Charles Mingus',
		released: 'May 22, 2004',
		year: 2004,
		era: 'Blogging Roots',
		knownFor: 'Plugin architecture',
		detail: 'Plugin hooks, localization, encrypted passwords, subcategories, and previewing gave WordPress its first real extension story.',
		artifact: 'Plugin hook fishing rod',
		blueprint: './blueprints/wordpress-museum/wp-1-2.json',
	},
	{
		version: '1.0',
		name: 'Miles',
		musician: 'Miles Davis',
		released: 'January 3, 2004',
		year: 2004,
		era: 'Blogging Roots',
		knownFor: 'Permalinks and moderation',
		detail: 'The first named WordPress release added search-friendly permalinks, multiple categories, comment moderation, and an early setup wizard.',
		artifact: 'Permalink fossil',
		blueprint: './blueprints/wordpress-museum/wp-1-0.json',
	},
	{
		version: '0.7',
		name: '',
		musician: '',
		released: 'May 27, 2003',
		year: 2003,
		era: 'Blogging Roots',
		knownFor: 'The first WordPress',
		detail: 'The very first public release, forked from b2/cafelog. It shipped before the jazz-codename tradition began at 1.0, so it carries no musician name.',
		artifact: 'b2/cafelog fork stone',
		blueprint: './blueprints/wordpress-museum/wp-0-7.json',
	},
];

window.WP_MUSEUM_ERAS = [
	'Blogging Roots',
	'Dashboard Foundations',
	'CMS Toolkit',
	'Modern Admin',
	'API and Customizer',
	'Block Editor',
	'Blocks Everywhere',
];
